### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rokit** [CLevasseur/ta-lib-rust#9]
https://github.com/CLevasseur/ta-lib-rust/blob/133c10b20416662c947bd8cbe410b8c2eaed526b/examples/sma.rs#L46

If the period is 10, shouldn't the above comment say 9 instead of 29?

**Comment by CLevasseur** [comment]
Absolutely, feel free to open a pull request with the right index value and I'll merge it.

**Comment by rokit** [comment]
Thanks, I was just browsing your code since I'm doing something similar and wanted to make sure I wasn't missing something.
